[project]
name = "music-storage-mgr"
version = "0.1.0"
description = "Music Storage Manager Web Interface"
readme = "README.txt"
requires-python = ">=3.13"
dependencies = [
    "Flask==2.3.3",
    "Werkzeug==2.3.7",
    "pywebview==4.4.1",
    "requests==2.31.0",
]
